[package]

name = "lis2de12"
version = "0.0.2"
authors = ["Conor Forde"]
edition = '2018'

repository = "https://www.github.com/Snowda/LIS2DE12"

description = "LIS2DE12 driver"
keywords = ["LIS2DE12", "hardware", "accelerometer"]

[[bin]]
name = "test"
path = "src/lib.rs"

[dependencies]
embedded-hal = "0.2.6"